<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringListToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmdbXQlsaXN0ID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5KCBwaXBlbGlu
ZUN1cnNvciwgImxpc3QiICk7IA0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpTdHJpbmdK
b2luZXIgam9pbmVyID0gbmV3IFN0cmluZ0pvaW5lcigiLCAiKTsNCmZvciAoU3RyaW5nIGVsZW1l
bnQgOiBsaXN0KSB7DQpqb2luZXIuYWRkKGVsZW1lbnQpOw0KfQ0KDQovLyBwaXBlbGluZQ0KSURh
dGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInN0cmluZyIsIGpvaW5lci50b1N0cmluZygpICk7
DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
